name: kumulaau
channels:
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2018.12.5
  - certifi=2018.11.29
  - cycler=0.10.0
  - intel-openmp=2019.1
  - mkl=2019.1
  - pip=18.1
  - pyparsing=2.3.1
  - python-dateutil=2.7.5
  - pytz=2018.9
  - setuptools=40.6.3
  - six=1.12.0
  - wheel=0.32.3
  - numba=0.42.0
  - freetype=2.9.1
  - tk=8.6.8
  - libedit=3.1.20181209
  - xz=5.2.4
  - llvmlite=0.27.0
  - ncurses=6.1
  - numpy=1.15.4
  - tornado=5.1.1
  - python=3.7.2
  - mkl_fft=1.0.10
  - mkl_random=1.0.2
  - numpy-base=1.15.4
  - sqlite=3.26.0
  - libffi=3.2.1
  - readline=7.0
  - libpng=1.6.36
  - kiwisolver=1.0.1
  - zlib=1.2.11
  - matplotlib=3.0.2
  - openssl=1.1.1a
  - scipy=1.2.0

