#!/usr/bin/env python3
from __future__ import annotations

from numpy import ndarray, array, asarray, sqrt
from abc import ABC, abstractmethod
from typing import List, Iterable
from argparse import Namespace
import pop


class Model(ABC):
    @abstractmethod
    def _generate_topology(self, theta) -> List:
        """ Generate a list of pointers to trees generated by the pop module. The pop_trace() method
        must be used here.

        :param theta: Parameter set to use with tree tracing.
        :return: List of pointers to C structures in pop module, order maintained by child class.
        """
        raise NotImplementedError

    @abstractmethod
    def _resolve_lengths(self, i_0: ndarray) -> ndarray:
        """ Generate a list of lengths, whose topology is determined by the child class. The pop_evolve() must be used
        here.

        :return: List of repeat lengths.
        """
        raise NotImplementedError

    def __init__(self, theta):
        """ Constructor. Bind our parameter set theta and build our trees.

        :param theta: A parameter set for the given population model.
        """
        self.is_evolved, self.evolved = False, array([])  # Our default values.
        self.theta = theta  # Save our parameter set.

        # Trace our trees. The result should return pointers to one or more C structures.
        self.generate_topology_results = self._generate_topology(theta)

    def evolve(self, i_0: ndarray) -> ndarray:
        """ Using the common ancestors 'i_0', evolve the population until '2n' alleles are present.

        :param i_0 Array of starting common ancestors.
        :return: The evolved generation from the common ancestor.
        """
        if self.is_evolved:  # If we have evolved, then return what we currently have. Otherwise, raise our flag.
            return self.evolved
        else:
            self.is_evolved = True

        # Verify that number of seed lengths passed is a triangle number.
        if 0.5 * (sqrt(8 * len(i_0) + 1) - 1) % 1 != 0:
            raise ValueError("i_0 is not a triangle number.")

        # Evolve our population using the tree(s) generated at instantiation.
        self.evolved = self._resolve_lengths(i_0)

        # Return the evolved generation of ancestors.
        return self.evolved

    @staticmethod
    def pop_trace(n, f, c, d, kappa, omega):
        """ A wrapper for the pop module trace method.

        :param n: Population size, used for determining the number of generations between events.
        :param f: Scaling factor for the total mutation rate. Smaller = shorter time to coalescence.
        :param c: Constant bias for the upward mutation rate.
        :param d: Linear bias for the downward mutation rate.
        :param kappa: Lower bound of repeat lengths.
        :param omega: Upper bound of repeat lengths.
        :return: Pointer to a pop module C structure (tree).
        """
        return pop.trace(n, f, c, d, kappa, omega)

    @staticmethod
    def pop_evolve(p, i_0: Iterable) -> ndarray:
        """ A wrapper for the pop module evolve method.

        :param p: Pointer to a pop module C structure (tree)
        :param i_0: Array of starting lengths.
        :return: Array of repeat lengths.
        """
        return asarray(pop.evolve(p, [i for i in i_0]))


def get_arguments() -> Namespace:
    """ Create the CLI and parse the arguments, if used as our main script.

    :return: Namespace of all values.
    """
    from argparse import ArgumentParser

    parser = ArgumentParser(description='Simulate the evolution of single population.')
    list(map(lambda a: parser.add_argument(a[0], help=a[1], type=a[2], nargs=a[3]), [
        ['-image', 'Image file to save resulting repeat length distribution (histogram) to.', str, None],
        ['-i_0', 'Repeat lengths of starting ancestors.', int, '+'],
        ['-n', 'Starting population size.', int, None],
        ['-f', 'Scaling factor for total mutation rate.', float, None],
        ['-c', 'Constant bias for the upward mutation rate.', float, None],
        ['-d', 'Linear bias for the downward mutation rate.', float, None],
        ['-kappa', 'Lower bound of repeat lengths.', int, None],
        ['-omega', 'Upper bound of repeat lengths.', int, None]
    ]))

    return parser.parse_args()


if __name__ == '__main__':
    from timeit import default_timer as timer
    from numpy import std, average
    from matplotlib import use

    arguments = get_arguments()  # Parse our arguments.

    use('TkAgg')  # Use a different backend (plotting to display).
    from matplotlib import pyplot as plt

    # Evolve some population 1000 times.
    start_t = timer()
    main_descendants = [pop.evolve(pop.trace(arguments.n,
                                             arguments.f,
                                             arguments.c,
                                             arguments.d,
                                             arguments.kappa,
                                             arguments.omega),
                                   arguments.i_0) for _ in range(1000)]
    end_t = timer()
    print('Time Elapsed (10000x): [\n\t' + str(end_t - start_t) + '\n]')

    # Determine the variance and mean of the generated populations.
    print('Mean (10000x): [\n\t' + str(average(main_descendants)) + '\n]')
    print('Deviation (10000x): [\n\t' + str(std(main_descendants)) + '\n]')

    # Display a histogram of the first generated populace.
    plt.hist(main_descendants[0], bins=range(min(main_descendants[0]), max(main_descendants[0])))
    plt.savefig(arguments.image) if arguments.image is not None else plt.show()
